# Generated by Django 4.1.6 on 2023-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesuggession',
            name='difficulty',
            field=models.CharField(choices=[('BG', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='BG', max_length=2),
        ),
    ]
