# Generated by Django 4.1.6 on 2023-07-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='team_detail',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
