# Generated by Django 4.1.6 on 2023-07-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_otp_team_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='team_detail',
            new_name='assigned_to',
        ),
    ]
