# Generated by Django 4.1.6 on 2023-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_coursesuggession_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
