# Generated by Django 4.1.6 on 2023-02-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quizuserscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuserscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
