# Generated by Django 4.1.6 on 2023-07-25 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_rename_team_detail_otp_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_exp_with_STS', models.CharField(max_length=50)),
                ('expectation_in_assisting_tech_transition', models.CharField(max_length=50)),
                ('exp_in_navigation_finding_features', models.CharField(max_length=50)),
                ('quiz_engaging_and_interactive', models.CharField(max_length=50)),
                ('quiz_evaluation_of_tech_accuration', models.CharField(max_length=50)),
                ('udm_yt_recom_helpful', models.CharField(max_length=50)),
                ('cs_align_withur_curt_knowledge_levl', models.CharField(max_length=50)),
                ('conveniency_accessing_recom_yt_cs', models.CharField(max_length=50)),
                ('mylearningpage_layout_presentation', models.CharField(max_length=50)),
                ('valueof_progs_tracking_feature_on_dashboard', models.CharField(max_length=50)),
                ('motivate_to_complete_course', models.CharField(max_length=50)),
                ('specific_feature_you_feel_missing', models.CharField(max_length=1000)),
                ('how_app_enhanced', models.CharField(max_length=1000)),
                ('technical_prob_performance_issue', models.CharField(max_length=1000)),
                ('exp_anythingelse_about_STS', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
