# Generated by Django 4.1.6 on 2023-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSuggession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('course_ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'course_suggestion',
            },
        ),
    ]
