# Generated by Django 4.1.6 on 2023-06-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_otp_username_remove_quizattempt_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursesuggession',
            options={'verbose_name_plural': 'Course Suggestion'},
        ),
    ]
