# Generated by Django 4.1.7 on 2023-02-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_coursesuggession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuserscore',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
