# Generated by Django 4.1.7 on 2023-02-23 07:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_quizuserscore_created_at_alter_question_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuserscore',
            name='user',
            field=models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
