# Generated by Django 4.1.6 on 2023-06-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuserscore',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
