# Generated by Django 4.1.7 on 2023-02-28 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.OneToOneField(default=45646, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
