# Generated by Django 4.1.6 on 2023-07-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_quizuserscore_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeractivity',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playeractivity',
            name='youtube_id',
            field=models.CharField(default='', max_length=25),
        ),
    ]
