# Generated by Django 4.1.6 on 2023-07-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_playeractivity_percentage_playeractivity_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeractivity',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
