# Generated by Django 4.1.7 on 2023-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_otp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
