# Generated by Django 4.1.6 on 2023-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_playeractivity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeractivity',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
