# Generated by Django 4.1.7 on 2023-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_otp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default=1123, max_length=50),
            preserve_default=False,
        ),
    ]
