# Generated by Django 4.1.7 on 2023-03-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_otp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesuggession',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='coursesuggession',
            name='course_ratings',
        ),
        migrations.RemoveField(
            model_name='coursesuggession',
            name='score',
        ),
        migrations.RemoveField(
            model_name='coursesuggession',
            name='source',
        ),
        migrations.AddField(
            model_name='coursesuggession',
            name='difficulty',
            field=models.CharField(choices=[('BG', 'Begginer'), ('IN', 'Intermediat'), ('AD', 'Advanced')], default='BG', max_length=2),
        ),
        migrations.AlterField(
            model_name='coursesuggession',
            name='course_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='coursesuggession',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
