# Generated by Django 4.1.6 on 2023-07-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
