# Generated by Django 4.1.7 on 2023-03-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_coursesuggession_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesuggession',
            name='difficulty',
            field=models.CharField(choices=[('BG', 'Begginer'), ('IN', 'Intermediat'), ('AD', 'Advanced')], default='BG', max_length=2),
        ),
        migrations.AlterField(
            model_name='coursesuggession',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggesstion', to='home.category'),
        ),
    ]
