# Generated by Django 4.1.7 on 2023-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_coursesuggession_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesuggession',
            name='difficulty',
            field=models.CharField(choices=[('BG', 'Begginer'), ('IN', 'Intermediat'), ('AD', 'Advanced')], max_length=2),
        ),
    ]
