# Generated by Django 4.1.7 on 2023-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_coursesuggession_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuserscore',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
