# Generated by Django 4.1.7 on 2023-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_quizuserscore_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesuggession',
            name='course_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursesuggession',
            name='course_instructor',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='coursesuggession',
            name='course_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='coursesuggession',
            name='ratings',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='coursesuggession',
            name='difficulty',
            field=models.CharField(choices=[('BG', 'Begginer'), ('IN', 'Intermediat'), ('AD', 'Advanced')], default='BG', max_length=2),
        ),
    ]
