# Generated by Django 4.1.7 on 2023-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_coursesuggession_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesuggession',
            name='course_duration',
            field=models.FloatField(null=True),
        ),
    ]
