# Generated by Django 4.1.6 on 2023-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_coursesuggession_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.IntegerField(default=0)),
                ('domain', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='otp',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
