# Generated by Django 4.1.6 on 2023-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_quizuserscore_quiz_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuserscore',
            name='quiz_domain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
