# Generated by Django 4.1.6 on 2023-05-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_quizuserscore_quiz_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
