# Generated by Django 4.1.6 on 2023-05-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_otp_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuserscore',
            name='suggested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.coursesuggession'),
        ),
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('continue_link', models.CharField(blank=True, max_length=200, null=True)),
                ('user_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizuserscore')),
            ],
        ),
    ]
